name: Firebase App Distribution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  assemble:
    name: Assemble Apk
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Update release notes with name of the Feature.
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Update release notes.
        run: |
          echo : > app/release_notes_firebase.txt
          echo $BRANCH_NAME > app/release_notes_firebase.txt



      # Build app & publish apk to firebase
      - name: Auth to Google Cloud
        id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Build & Deploy
        run: |
          ./gradlew --stop
          ./gradlew clean
          ./gradlew assembleDebug  appDistributionUploadDebug

